apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    run: weather-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: weather-app-service
